apiVersion: v1
kind: Pod 
metadata:
  name: db-pod
  namespace: dev-database
  labels:
    tier: database 

spec: 
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo 'I survived' >> /data/proof.txt && sleep 3600"]
    volumeMounts: 
    - name: db-storage
      mountPath: /data 
    
  volumes: 
  - name: db-storage 
    persistentVolumeClaim:
      claimName: db-pvc