apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-pod
  namespace: dev-backend
spec:
  serviceAccountName: readonly-sa
  containers:
  - name: app
    image: bitnami/kubectl
    command: ["sleep", "3600"]