apiVersion: v1 
kind: Pod 
metadata: 
  name: about-to-be-evicted
  namespace: dev-backend
  labels:
    app: about-to-be-evicted
spec:
  containers:
  - name: app 
    image: busybox 
    command: ["sh", "-c", "sleep 3600"]