apiVersion: v1
kind: Pod
metadata:
  name: before-taint
  namespace: dev-backend
  labels:
    app: before-taint
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]