apiVersion: v1
kind: Pod
metadata:
  name: no-toleration
  namespace: dev-backend
  labels:
    app: no-toleration
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]