apiVersion: v1
kind: Pod 
metadat:  
  name: with-toleration 
  namespace: dev-backend
  labels:
    app: with-toleration

spec: 
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "backend-only"
    effects: "NoSchedule"
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]