apiVersion: v1
kind: Pod
metadata:
  name: affinity-required
  namespace: dev-backend
  labels:
    app: affinity-required
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
            - nvme
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]