apiVersion: v1
kind: Pod
metadata:
  name: affinity-preferred
  namespace: dev-backend
  labels:
    app: affinity-preferred
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - nvme
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]