apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-fail
  namespace: dev-backend
  labels:
    app: nodeselector-fail
spec:
  nodeSelector:
    disktype: hdd
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]