apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-demo
  namespace: dev-backend
  labels:
    app: nodeselector-demo
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]