apiVersion: v1
kind: Pod 
metadata:
  name: multi-pod

spec: 
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
      - containerPort: 80
    - name: logger
      image: busybox
      command: ["sh", "-c", "while true; do echo logging at $(date); sleep 5; done"]