apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: config-demo
  namespace: dev-backend
  labels:
    app: config-demo
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: config-demo
  template:
    metadata:
      labels:
        app: config-demo
    spec: 
      containers:
      - name: app
        image: busybox
        command: ["sh", "-c", "env | grep -E 'APP_ENV|LOG_LEVEL|FEATURE' && sleep 3600"]
        # env: 
        # - name: APP_ENV
        #   valueFrom: 
        #     configMapKeyRef:
        #       name: app-config
        #       key: APP_ENV
        # - name: LOG_LEVEL 
        #   valueFrom:
        #     configMapKeyRef:
        #       name: app-config
        #       key: LOG_LEVEL
        envFrom:
        - configMapRef:
            name: app-config