apiVersion: v1 
kind: Pod 
metadata:
  name: config-file-demo
  namespace: dev-backend
spec: 
  containers:
  - name: app 
    image: busybox 
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes: 
  - name: config-volume
    configMap: 
      name: nginx-conf