apiVersion: v1
kind: Pod 
metadata:
  name: init-fail
  namespace: dev-backend
  labels:
    app: init-fail

spec: 
  initContainers:
  - name: init-broken
    image: busybox
    command: ["sh", "-c", "echo 'Trying...' && exit 1"]
  containers:
  - name: main-app  
    image: busybox
    command: ["sh", "-c", "echo 'I should never run' && sleep 3600"]
    