apiVersion: v1
kind: Pod 
metadata:
  name: init-demo
  namespace: dev-backend
  labels:
    app: init-demo

spec:
  initContainers:
  - name: init-setup
    image: busybox
    command: ["sh", "-c", "echo 'Init running...' && sleep 5 && echo 'Init done' > /shared/ready.txt"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  containers:
  - name: main-app
    image: busybox
    command: ["sh", "-c", "echo 'Main app started' && cat /shared/ready.txt && sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  volumes:
  - name: shared-data
    emptyDir: {}