apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
  namespace: dev-backend
spec:
  containers:
  - name: app
    image: polinux/stress
    resources:
      requests:
        memory: "64Mi" 
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
