apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: replicaset 
  labels:
    app: nginx-demo
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: 
          nginx-demo
    spec: 
      containers:
      - name: nginx 
        image: nginx:latest
        ports:
        - containerPort: 80 